#
# Pre-commit configuration
#
# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [svg, sql]
      - id: trailing-whitespace
        # Trailing should remain in markdown files
        exclude_types: [markdown, sql]
        exclude: |
          (?x)^(
            .*/.bumpversion  # bum2version leaves trailing spaces
          )

  - repo: https://github.com/psf/black
    # See https://github.com/psf/black/issues/2493
    # rev: 26.3.1
    rev: 'refs/tags/26.3.1:refs/tags/26.3.1'
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check

  - repo: local
    hooks:
      - id: repository-policy
        name: Check repository policy
        entry: pre_commit_hooks/repository_policy.py
        language: script
        pass_filenames: false
